name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@71efad841d4b7bb6a479984abacf7111ebd44a16

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
